name: credit_card_field
description: Flutter credit card and expiration form fields
version: 1.0.0
author: Matthew Whitaker <sub6resources@gmail.com>
homepage: https://github.com/Sub6Resources/credit_card_field

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

